#ifndef ERRORS_H
#define ERRORS_H

typedef enum {
	ERROR_NONE = 0,
	ERROR_FILE_NOT_FOUND,
	ERROR_INVALID_ARGUMENTS,
	ERROR_FILE_READ,
	ERROR_FILE_WRITE,
	ERROR_MEMORY_ALLOCATION,
	ERROR_LEXEM_MISMATCH,
	ERROR_UNKNOWN_FLAG
} ErrorCode;

#endif
